version: "3.3"
services:
  serverboard:
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #   - 80
    ports:
      - 50000:3000
    networks:
      - boardNetwork
    volumes:
      - ./db:/app/db


networks:
  boardNetwork:
